package web.app.resources;
// Generated 30 Sep, 2019 11:09:42 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEES", schema = "HR" )
public @Data class Employees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private Integer employeeId;
	
	private Integer departmentId;
	private Integer managerId;
	
	private String jobId;
		
	private String firstName;
	private String lastName;
	private String email;
	private String phoneNumber;
	
	private Date hireDate;
	
	private BigDecimal salary;
	private BigDecimal commissionPct;
	
	
}
